name = "Feed the Moth"
author = "Chesapeake"
version = "0.0.1b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f54bee33e152999352892951c8377c2165ebbd474088e1e02accf06eb9946780"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
