name = "Feed the Moth"
author = "chesapeake"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fbaa05daa053be7516d02bae6912aee20a693052b71c51e4fef4f3f2985a454"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
